export { default as Home } from './home'
export { default as Auth } from './Auth'
export { default as Orders } from './Orders'
export { default as Tables } from './Tables'
export { default as Menu } from './Menu'